### ISSUE TITLE
detect_outdated_consent may calculate wrong timestamp

### ISSUE THREAD

**Issue by lmgualandi** [bocops/UMP-workarounds#13]
base64 string is apparently missing one character that may appear in the IABTCF_TCString string: '-'
An IABTCF_TCString generated today 03/05/24 is including the '-' character and the timestamp generated is consequentially wrong.

I made the following modification by adding the dash before the plus sign and it seems to have worked. I'm not sure if the las two characters are correct now, though.

`String base64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-+/";`

**Comment by bocops** [comment]
Hi there, thanks for the issue report. IAB TCF's documentation now clarifies that the TC String is _base64url_ encoded, not sure if this wasn't publicly documented before or if I've just not seen it. In this case, the correct alphabet to use would be:

`String base64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";`

**Comment by bocops** [comment]
Now fixed in both JAVA and Kotlin code.

**Comment by AndroidDeveloperLB** [comment]
@bocops Can you please also update when goodVendorConfiguration changes?
I've noticed that it changes out of nothing, making it hard to notice...
