### ISSUE TITLE
Bug: deleteTCStringIfOutdated tries to delete even when it has no value found

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [bocops/UMP-workarounds#3]
As the title says.

This line makes sure there is a value, and so later it finds the timestamp is of 19707 days ago, and tries to delete:

```
        val tcString = sharedPrefs
            .getString("IABTCF_TCString", "AAAAAAA") ?: "AAAAAAA"
```

As this is the only place to reach the sharedPreferences there, it's better to just return from the function once you see there is nothing to really read here from the key "IABTCF_TCString", and so no need to delete this key either.
Meaning as such:

```
        val tcString = sharedPrefs
            .getString("IABTCF_TCString", null) ?: return
```

**Comment by bocops** [comment]
I wouldn't consider this a bug, but you are correct that this performs an unnecessary check. Thanks for bringing this up.

**Comment by AndroidDeveloperLB** [comment]
A minor bug then. Not all bugs cause terrible issues.
